import { User } from "../models/user.model";

export interface ChatMessage{
    senderId?: string;
    userName:string;
    content: string;
    createdAt?:Date;
}

export interface oldChatResponse{
     sender: User;
    userName:string;
    content: string;
    createdAt?:Date;
}

export interface FormateMessages{
    senderId?:string;
   userName?:string;
   content: string;
   sentByUser?:boolean
}

export interface PollOption {
    name: string;
    votes: number;
  }
  
export interface PollData {
_id?: string;    
userId?:string;     // Optional: generated by the backend
question: string;     // Poll question
options: PollOption[]; // Array of poll options
totalVotes?: number;  // Optional: can be calculated on the backend
submitted?:string[]
createdBy?:string
}
